---
twitter: https://twitter.com/imShreyasPatil
github: https://github.com/PatilShreyas
linkedin: https://www.linkedin.com/in/patil-shreyas
youtube: https://www.youtube.com/channel/UCKD_CXX0Yd449_Ns2I1cXcg
dribbble: ''
instagram: https://instagram.com/_patilshreyas/
facebook: https://www.facebook.com/shreyaspatil99
medium: https://medium.com/@patilshreyas
patreon: ''
paypal: https://www.paypal.me/PatilShreyas99/
unsplash: ''
